CREATE DATABASE museum;
USE museum;
CREATE TABLE museo (
museo_id INT  PRIMARY KEY AUTO_INCREMENT,
nombre VARCHAR  (150) NOT NULL,
direccion VARCHAR  (150) NOT NULL
);
DROP DATABASE museum;
CREATE TABLE cuadro (
cuadro_id INT  PRIMARY KEY AUTO_INCREMENT,
autor VARCHAR  (150) NOT NULL,
titulo VARCHAR  (150) NOT NULL
sala_id INT  PRIMARY KEY AUTO_INCREMENT,
museo_id
CONSTRAINT fk_sala_id_1 FOREIGN KEY (sala_id) REFERENCES cuadro (department_id) ON DELETE CASCADE ON UPDATE CASCADE


CREATE TABLE sala (
sala_id INT  PRIMARY KEY AUTO_INCREMENT,
museo_id
titulo VARCHAR  (150) NOT NULL

);